export const projects = [
  {
    id: "01",
    title: "clix",
    subtitle: "Linux Command Helper",
    year: "2025",
    href: "https://github.com/ManojMJ17/clix",
    img: "/images/linux2.jpeg",
    video: "/videos/clix_demo.mp4",
  },
  {
    id: "02",
    title: "RhythmBox",
    subtitle: "Spotify clone",
    year: "2023",
    href: "https://spotify-clone-gules-alpha.vercel.app/",
    img: "/images/spotify-musicl-bg.jpeg",
    video: "/videos/Spotify_project.mp4",
  },
  {
    id: "03",
    title: "Socially",
    subtitle: "Social Networking Platform",
    year: "2024",
    href: "https://socially-sable.vercel.app/",
    img: "/images/socially.jpeg",
    video: "/videos/Socially_project.mp4",
  },
  {
    id: "04",
    title: "Awwward Winning Website",
    subtitle: "Gaming Website",
    year: "2024",
    href: "https://gaming-website-with-gsap.vercel.app/",
    img: "/images/Website.jpeg",
    video: "/videos/awward_winning_website_project.mp4",
  },
  {
    id: "05",
    title: "Digital Library",
    subtitle: "University Library System",
    year: "2024",
    href: "https://university-library-lime.vercel.app/",
    img: "/images/library-bg.jpeg",
    video: "/videos/BookWise_project.mp4",
  },
  {
    id: "06",
    title: "PrepMate",
    subtitle: "Exam Preparation Assistance",
    year: "2025",
    href: "https://interview-prep-tau-azure.vercel.app/",
    img: "/images/exam-bg.jpeg",
    video: "/videos/prepmate_project.mp4",
  },
];
