import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Toaster } from "sonner";

const neueMontrealRegular = localFont({
  src: "/fonts/NeueMontreal-Regular.woff2",
  variable: "--font-montreal-regular",
  display: "swap",
});

// Load Medium
const neueMontrealMedium = localFont({
  src: "/fonts/NeueMontreal-Medium.woff2",
  variable: "--font-montreal-medium",
  display: "swap",
});

const neueMontrealLight = localFont({
  src: "/fonts/NeueMontreal-Light.woff2",
  variable: "--font-montreal-light",
  display: "swap",
});

const azeretMonoLight = localFont({
  src: "/fonts/AzeretMono-Light.ttf",
  variable: "--font-azeretMono-light",
});

const azeretMonoRegular = localFont({
  src: "/fonts/AzeretMono-Regular.ttf",
  variable: "--font-azeretMono-regular",
});

const consola = localFont({
  src: "/fonts/CONSOLA.ttf",
  variable: "--font-consola",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${neueMontrealLight.variable} ${neueMontrealMedium.variable} ${neueMontrealRegular.variable} ${azeretMonoLight.variable} ${azeretMonoRegular.variable} ${consola.variable} antialiased`}
      >
        <Toaster position="top-center" closeButton />
        {children}
      </body>
    </html>
  );
}
